version: '3.8'

# Definição de serviços
services:
  # Serviço principal da aplicação web
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - DEBUG=True
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_VERIFY_SID=${TWILIO_VERIFY_SID}
      - SMS_CODE_EXPIRY_MINUTES=5
      - REDIS_HOST=redis
    env_file:
      - .env
    volumes:
      - .:/app
      - ./app/static:/app/app/static
      - ./app/templates:/app/app/templates
      - ./data:/app/data
    depends_on:
      - redis
      - qdrant
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - psicollab-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Serviço Redis para cache
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - psicollab-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Serviço Qdrant para busca vetorial
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT_ALLOW_CORS=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - psicollab-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Definição de volumes
volumes:
  qdrant_data:
    name: psicollab_qdrant_data
  redis_data:
    name: psicollab_redis_data

# Definição de redes
networks:
  psicollab-network:
    name: psicollab_network
    driver: bridge 