version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - DEBUG=True
    env_file:
      - .env
    volumes:
      - ./static:/app/static
      - ./data:/app/data
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT_ALLOW_CORS=true

volumes:
  qdrant_data:

networks:
  psicollab-network:
    driver: bridge 